repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-byte-order-marker
- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  -   id: reorder-python-imports
